plugins {
    id "com.android.application"
}

android {
    namespace "ru.romentiy.gacgs8manual"
    compileSdk 35

    defaultConfig {
        applicationId "ru.romentiy.gacgs8manual"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug { }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
